databases:
  - name: nextolke-db
    plan: free
    region: oregon
    ipAllowList: [] # Optional: empty means accessible internally by other Render services

services:
  - type: web
    name: nextolke-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      gunicorn nextolk.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nextolke-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: du5z4g1jl
      - key: CLOUDINARY_API_KEY
        value: 912456986662768
      - key: CLOUDINARY_API_SECRET
        value: gduKAmp6kQy1H7BHYC9QNmwMPeU
      - key: RENDER
        value: True
      - key: WEB_CONCURRENCY
        value: 4