# render.yaml
# Place this file at the root of your Django project's GitHub repository

services:
  # ----------------------------------------------------------------------
  # 1. PostgreSQL Database Service
  # This defines your persistent database.
  # ----------------------------------------------------------------------
  - type: "pserv"
    name: "nextolk-db"
    plan: "starter"
    region: "oregon"
    # Optional: Define a connection string variable for explicit referencing
    # This will create an environment variable named DATABASE_URL in your web service
    # pointing to this database's internal connection string.
    # The value of this key will be the name of the environment variable created.
    # We will use this in the web service's envVars.
    # IMPORTANT: The 'connectionString' key is specific to Render's Blueprint
    # and tells it to generate a URL for this database.
    connectionString: "DATABASE_URL" # This key tells Render to create an ENV var named DATABASE_URL for this DB.

  # ----------------------------------------------------------------------
  # 2. Django Web Service
  # This defines your Django backend application.
  # ----------------------------------------------------------------------
  - type: "web"
    name: "nextolk-backend"
    env: "python"
    region: "oregon"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn nextolk.wsgi:application"
    # Adjust 'nextolk.wsgi:application' if your project's WSGI file is named differently

    # Environment variables for your Django application
    envVars:
      # Reference the DATABASE_URL that the 'nextolke-db' service exports
      # The 'fromService' key is used to pull an environment variable from another service
      # within the same Blueprint.
      - key: "DATABASE_URL"
        fromService:
          name: "nextolk-db"
          property: "connectionString" # This refers to the 'connectionString' defined on the database service
      - key: "SECRET_KEY"
        generateValue: true
      - key: "CLOUDINARY_CLOUD_NAME"
        value: "du5z4g1jl" # Your actual Cloudinary Cloud Name
      - key: "CLOUDINARY_API_KEY"
        value: "912456986662768" # Your actual Cloudinary API Key
      - key: "CLOUDINARY_API_SECRET"
        value: "gduKAmp6kQy1H7BHYC9QNmwMPeU" # Your actual Cloudinary API Secret
      - key: "RENDER"
        value: "True"
      - key: "WEB_CONCURRENCY"
        value: "4"