# render.yaml
# Place this file at the root of your Django project's GitHub repository

services:
  # ----------------------------------------------------------------------
  # 1. PostgreSQL Database Service
  # This defines your persistent database.
  # ----------------------------------------------------------------------
  - type: "pserv"
    name: "nextolk-db"
    plan: "starter"
    region: "oregon"
    # ipAllowList: [] # Optional: Restrict access by IP. Empty means accessible by other Render services.

  # ----------------------------------------------------------------------
  # 2. Django Web Service
  # This defines your Django backend application.
  # ----------------------------------------------------------------------
  - type: "web"
    name: "nextolk-backend"
    env: "python"
    region: "oregon"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn nextolk.wsgi:application"
    # Adjust 'nextolk.wsgi:application' if your project's WSGI file is named differently

    # Environment variables for your Django application
    envVars:
      - key: "DATABASE_URL"
        fromDatabase: "nextolk-db"
      - key: "SECRET_KEY"
        generateValue: true
      - key: "CLOUDINARY_CLOUD_NAME"
        value: "du5z4g1jl" # Your actual Cloudinary Cloud Name
      - key: "CLOUDINARY_API_KEY"
        value: "912456986662768" # Your actual Cloudinary API Key
      - key: "CLOUDINARY_API_SECRET"
        value: "gduKAmp6kQy1H7BHYC9QNmwMPeU" # Your actual Cloudinary API Secret
      - key: "RENDER"
        value: "True"
      - key: "WEB_CONCURRENCY"
        value: "4"