# Generated by Django 5.2.3 on 2025-07-05 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 13, 28, 23, 55165, tzinfo=datetime.timezone.utc)),
        ),
    ]
