# Generated by Django 5.2.3 on 2025-07-05 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 15, 36, 35, 607580, tzinfo=datetime.timezone.utc)),
        ),
    ]
