# Generated by Django 5.2.3 on 2025-07-06 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 6, 6, 11, 4, 190354, tzinfo=datetime.timezone.utc)),
        ),
    ]
