# Generated by Django 5.2.3 on 2025-07-06 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 6, 14, 38, 5, 979231, tzinfo=datetime.timezone.utc)),
        ),
    ]
