# Generated by Django 5.0.6 on 2025-07-07 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 21, 18, 32, 201660, tzinfo=datetime.timezone.utc)),
        ),
    ]
