# Generated by Django 5.0.6 on 2025-07-08 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 13, 35, 9, 972615, tzinfo=datetime.timezone.utc)),
        ),
    ]
