# Generated by Django 5.0.6 on 2025-07-09 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 11, 4, 53, 291054, tzinfo=datetime.timezone.utc)),
        ),
    ]
