# Generated by Django 5.0.6 on 2025-07-10 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 7, 0, 21, 896499, tzinfo=datetime.timezone.utc)),
        ),
    ]
