# Generated by Django 5.0.6 on 2025-07-10 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 8, 16, 31, 672416, tzinfo=datetime.timezone.utc)),
        ),
    ]
