# Generated by Django 5.0.6 on 2025-07-11 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 2, 45, 33, 843603, tzinfo=datetime.timezone.utc)),
        ),
    ]
