# Generated by Django 5.0.6 on 2025-07-12 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 10, 0, 34, 601908, tzinfo=datetime.timezone.utc)),
        ),
    ]
