# Generated by Django 5.0.6 on 2025-07-12 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 15, 28, 17, 357002, tzinfo=datetime.timezone.utc)),
        ),
    ]
