# Generated by Django 5.0.6 on 2025-07-12 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_video_is_live_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_live',
        ),
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 20, 17, 39, 280035, tzinfo=datetime.timezone.utc)),
        ),
    ]
