# Generated by Django 5.0.6 on 2025-07-12 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_remove_video_is_live_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 20, 18, 26, 943608, tzinfo=datetime.timezone.utc)),
        ),
    ]
