# Generated by Django 5.0.6 on 2025-07-13 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_video_is_live_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 6, 58, 53, 259242, tzinfo=datetime.timezone.utc)),
        ),
    ]
