# Generated by Django 5.0.6 on 2025-07-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_phonenumberotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 7, 48, 39, 205915, tzinfo=datetime.timezone.utc)),
        ),
    ]
